### ISSUE TITLE
Pre-live checklist

### ISSUE THREAD

**Issue by jobin212** [rc-postcard/rc-postcard#64]
- [ ] Give credits to new users
- [ ] Make sure to switch to live key
- [ ] Monitor lob usage
